language: python
dist: xenial
services:
  - docker

python:
  - 3.5
  - 3.6
  - 3.7

cache: pip

install:
  - pip install tox-travis
  - travis_retry bash ./scripts/get_cpachecker.sh
  #- travis_retry python ./scripts/get_z3.py ./cpachecker/scripts/
  - python setup.py install
  - pip install tox-travis

script:
  # trick to use Java 8 instead of default Java 11
  - export JAVA=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  - java -version
  - javac -version
  - tox
  - python ./scripts/check.py ./examples/transformed

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      pip install codecov && codecov;
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      docker push cmlapsu/shadowdp:latest;
    fi

jobs:
  include:
    - stage: deploy
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker build . -t cmlapsu/shadowdp;
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
            docker push cmlapsu/shadowdp:latest;
          fi

notifications:
  email: false
