sudo: false

language: python

python:
  - "3.6"

cache: pip

install:
  - java -version
  - javac -version
  - pip install tox-travis
  - travis_retry bash ./scripts/get_cpachecker.sh
  - travis_retry python ./scripts/get_z3.py ./cpachecker/scripts/

script:
  - bash ./scripts/check.sh ./examples

notifications:
  email: false
