sudo: false

language: python

python:
  - "3.6"

cache: pip

install:
  - java -version
  - javac -version
  - pip install tox-travis
  - travis_retry bash ./scripts/get_cpachecker.sh
  - travis_retry python ./scripts/get_z3.py ./cpachecker/scripts/

script:
  - ./cpachecker/scripts/cpa.sh -predicateAnalysis-linear ./examples/noisymax_t.c -preprocess -setprop solver.solver=smtinterpol
  - ./cpachecker/scripts/cpa.sh -predicateAnalysis-linear ./examples/noisymax_t.c -preprocess
  - ./cpachecker/scripts/cpa.sh -predicateAnalysis ./examples/noisymax_t.c -preprocess -setprop solver.solver=z3 || true
  - ./cpachecker/scripts/cpa.sh -predicateAnalysis ./examples/noisymax_t.c -preprocess

notifications:
  email: false
