language: python
dist: xenial
services:
  - docker

python:
  - 3.5
  - 3.6
  - 3.7

cache: pip

install:
  - pip install tox-travis
  - travis_retry bash ./scripts/get_cpachecker.sh
  #- travis_retry python ./scripts/get_z3.py ./cpachecker/scripts/
  - python setup.py install
  - pip install tox-travis

script:
  # trick to use Java 8 instead of default Java 11
  - export JAVA=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  - java -version
  - javac -version
  - tox
  - python ./scripts/check.py ./examples/transformed

after_success:
  pip install codecov && codecov


jobs:
  include:
    - stage: deploy
      script:
        # test docker build
        - docker build . -t cmlapsu/shadowdp
        - docker run -it cmlapsu/shadowdp bash /shadowdp/scripts/benchmark.sh
        - docker run -it cmlapsu/shadowdp python3 /shadowdp/scripts/check.py /shadowdp/examples/transformed
      after_success:
        # only deploy on stable master branch
        - if [[ "$TRAVIS_BRANCH" = "master" && $TRAVIS_PULL_REQUEST = "false" ]]; then
            # push to docker hub
            echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin;
            docker push cmlapsu/shadowdp:latest;
            # push to github cmlapsu/shadowdp
            rm -rf .git;
            git init;
            git config user.name "Ryan Wang";
            git config user.email "ryanwang.cs@gmail.com";
            git add .;
            git commit -m "Release of ShadowDP.";
            git remote add origin https://ryanwanggit:$GITHUB_TOKEN@github.com/cmla-psu/shadowdp.git;
            git push -u --force origin master;
          fi

notifications:
  email: false
