sudo: false

language: python

python:
  - "3.6"

cache: pip

install:
  - java -version
  - javac -version
  - pip install tox-travis
  - travis_retry bash ./scripts/get_cpachecker.sh
  - travis_retry python ./scripts/get_z3.py ./cpachecker/scripts/
  - python setup.py install

script:
  - python ./scripts/check.py ./examples

notifications:
  email: false
